codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        tests:
          target: 100%
          paths:
            - "src/test/"
    patch:
      default:
        tests:
          target: 100%
          paths:
            - "src/test/"
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "src/main/java/com/andrewauclair/microtask/os"
  - "src/main/java/com/andrewauclair/microtask/Main.java"
