image: mightymalakai33/micro-task-docker:latest

stages:
  - build
  - test
  - quality_assurance
  - deploy

build:
  stage: build
  script:
    - ./create-version.sh
    - ./gradlew jar
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - build/reports/
      - build/test-results/

deploy:
  stage: deploy
  only:
    - tags

  script:
    - ./create-version.sh
    - ./gradlew jar
    - ./upload-release.sh
