image: mightymalakai33/micro-task:latest

stages:
  - build
  - depends
  - test
  - deploy

build-non-tag:
  stage: build
  except:
    - tags
  script:
    - ./create-version.sh
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week

build-tag:
  stage: build
  only:
    - tags
  script:
    - ./create-version.sh
    - ./gradlew jar
  artifacts:
    expire_in: never
    paths:
      - build/libs/

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - bash <(curl -s https://codecov.io/bash) -y ./codecov.yml -t "${CODECOV_TOKEN}"
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - build/reports/
      - build/test-results/

depends:
  stage: build
  script:
    - chmod +x ./check-dependencies.sh
    - ./check-dependencies.sh
  allow_failure: true

#deploy:
#  stage: deploy
#  only:
#    - tags
#
#  script:
#    - ./create-version.sh
#    - ./gradlew jar
#    - ./upload-release.sh
