image: openjdk:11.0.3-jdk

stages:
  - build
  - test
  - quality_assurance
  
build:
  stage: build
  script:
    - source ./ci/pre-build.sh
    - ./maven/bin/mvn package
  artifacts:
    paths:
      - target/
    expire_in: 1 week
   
test:
  stage: test
  script:
    - source ./ci/pre-build.sh
    - ./maven/bin/mvn test
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/tests/

    