image: openjdk/11.0.3-jdk:latest

stages:
  - build
  - test
  - quality_assurance
  
assembleDebug:
  stage: build
  script:
    - source ./ci/pre-build.sh
    - ./maven/bin/mvn package
  artifacts:
    paths:
      - target/
    expire_in: 1 week
   
unit_tests:
  stage: test
  script:
    - source ./ci/pre-build.sh
    - ./maven/bin/mvn test
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/tests/

    